name       : libinput-gestures
version    : 2.15
release    : 1
source     :
    - https://github.com/bulletmark/libinput-gestures/archive/2.15.tar.gz : 95a91a2c7c4c9f91c035f7defb6868a92f6c61218d0fcb0a87b0fa63527c2912
license    : GPL-3.0
component  : desktop
summary    : Background application to intercept and action libinput gestures from touchpad.
description: |
    Libinput-gestures is a utility which reads libinput gestures from your touchpad and maps them to gestures you configure in a configuration file. Each gesture can be configured to activate a shell command which is typically an xdotool command to action desktop/window/application keyboard combinations and commands.
rundeps    :
    - xdotool
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-stateless-configuration-and-use-it-by-defaul.patch
install    : |
    %make_install
    install -Dm644 $pkgfiles/libinput-gestures.conf $installdir/usr/share/libinput-gestures/libinput-gestures.conf
