name       : libinput-gestures
version    : 2.38
release    : 9
source     :
    - https://github.com/bulletmark/libinput-gestures/archive/2.38.tar.gz : 34ee3641b1337bf59105dfa246c38c72e7b91a8b05aa3b3b7d2e1eb09ef29c5c
license    : GPL-3.0-or-later
component  : desktop
summary    : Background application to intercept and action libinput gestures from touchpad
description: |
    Libinput-gestures is a utility which reads libinput gestures from your touchpad and maps them to gestures you configure in a configuration file. Each gesture can be configured to activate a shell command which is typically an xdotool command to action desktop/window/application keyboard combinations and commands.
rundeps    :
    - xdotool
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-stateless-configuration-and-use-it-by-defaul.patch
install    : |
    %make_install
    install -Dm00644 $pkgfiles/libinput-gestures.conf $installdir/usr/share/libinput-gestures/libinput-gestures.conf
